default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: cooktok_app_development

test:
  <<: *default
  database: cooktok_app_test

production:
  primary: &primary
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

  cache:
    <<: *primary
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary
    migrations_paths: db/cable_migrate
